apiRules:
- exclude:
    uidRegex: ^Discord\.API$
- exclude:
    uidRegex: ^Discord\.API.*$
- exclude:
    uidRegex: ^Discord\.Net\.Converters$
- exclude:
    uidRegex: ^Discord\.Net.*$
- exclude:
    uidRegex: ^RegexAnalyzer$